name: google_maps_flutter_geojson
description: Flutter package allows to display geojson data on Google Maps.
version: 0.0.1
author: Mateusz Kulpa
homepage: https://github.com/mateuszkulpa

environment:
  sdk: ">=2.3.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.0
  google_maps_flutter: ^0.5.21+8
  uuid: ^2.0.2
  
dev_dependencies:
  build_runner: ^1.6.1
  json_serializable: ^3.2.0
  
  flutter_test:
    sdk: flutter
flutter: